### PR TITLE
Cache optimizations

### PR DESCRIPTION
**Pull request by Samistine**

### CODE REVIEW

**Comment by mibby** [comment]
@Samistine Does this help permission lookup performance much?

**Comment by zml2008** [comment]
From looking at it, it doesn't look like it'd make much of a difference, and I don't really feel like spending a lot of time fiddling with performance in 1.x anyways, since 2.x is where everything interesting is happening, so I've kinda let this sit. If someone posts concrete results showing improvements I might merge it, but until then it'll just sit here.

**Comment by mibby** [comment]
@zml2008 2.x doesn't support bukkit (spigot) though and quite a few people are still on it / adamant about switching to sponge in its current state. :P 

Hopefully @Samistine will come back and discuss whether these optimizations are worth merging and/or benchmark differences. :P I could use all the optimizations in the world with my large permissions file.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.

**Pull request closed without merging**
