### PR TITLE
Ability to set chat color for groups

### PR DESCRIPTION
**Pull request by NIGHTMVRE**
Ability to set chat color for groups much like you set a prefix and suffix

### CODE REVIEW

**Comment by zml2008** [comment]
This
a) would be done in a chat plugin with no changes to PEX
b) is not a pull request -- no code is being submitted so this should have been an issue

**Comment by NIGHTMVRE** [comment]
what chat plugin because all the ones i have tried are un-successfu?l

**Comment by Stormbow** [comment]
The most commonly used plugin is EssentialsXChat, since most people use Essentials.

**Comment by NIGHTMVRE** [comment]
ok thx

**Pull request closed without merging**
